/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemagestionturnos;

import Clases.Turnos;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.xml.sax.SAXException;

/**
 *
 * @author Santos
 */
public class Generar_ticket extends javax.swing.JInternalFrame {
    private String ID;
    Turnos turno= new Turnos();
    int servCliente, pref, cajaRapida, cajaNormal, empresarial;
    /**
     * Creates new form Generar_ticket
     */
    public Generar_ticket() throws Exception {
        initComponents();
        ID=JOptionPane.showInputDialog(null,"Ingrese su ID","Sistema de tickets", HEIGHT);
        LocalDate fecha_actual = LocalDate.now();
        int ano_actual= fecha_actual.getYear();
        if ((ano_actual-Integer.valueOf(ID.substring(4, 8)))>=65) {
            this.ticket(2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonServCliente = new javax.swing.JButton();
        jButtonCaja = new javax.swing.JButton();
        jButtonPreferencial = new javax.swing.JButton();

        setClosable(true);

        jButtonServCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonServCliente.setText("Servicio al cliente");
        jButtonServCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServClienteActionPerformed(evt);
            }
        });

        jButtonCaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCaja.setText("Caja");
        jButtonCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCajaActionPerformed(evt);
            }
        });

        jButtonPreferencial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPreferencial.setText("Preferencial");
        jButtonPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreferencialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonServCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonServCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonServClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServClienteActionPerformed
        try {
            this.ticket(1);
        } catch (Exception ex) {
            Logger.getLogger(Generar_ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonServClienteActionPerformed

    private void jButtonCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCajaActionPerformed
        try {
            this.ticket(Integer.valueOf(JOptionPane.showInputDialog(null,"Elija una de las siguientes opciones.\n1.Caja Rapida.\n2.Caja Normal.\n3.Empresarial.","Eleccion de caja"))+2);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Por favor seleccione una opcion valida");
        }
        
    }//GEN-LAST:event_jButtonCajaActionPerformed

    private void jButtonPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreferencialActionPerformed
        try {
            this.ticket(2);
        } catch (Exception ex) {
            Logger.getLogger(Generar_ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPreferencialActionPerformed
    
    private void ticket(int categoria) throws Exception{
        switch(categoria){
            case 1:
                turno.Comprobacion(categoria, "Servicio al cliente");
                turno.ticketGenerado(categoria,"Servicio al cliente", LocalDateTime.now());
                break;
            case 2:
                turno.Comprobacion(categoria, "Preferencial");
                turno.ticketGenerado(categoria, "Preferencial", LocalDateTime.now());
                break;
            case 3:
                turno.Comprobacion(categoria, "Caja Rapida");
                turno.ticketGenerado(categoria, "Caja Rapida", LocalDateTime.now());
                break;
            case 4:
                turno.Comprobacion(categoria, "Caja Normal");
                turno.ticketGenerado(categoria, "Caja Normal", LocalDateTime.now());
                break;
            case 5:
                turno.Comprobacion(categoria, "Empresarial");
                turno.ticketGenerado(categoria, "Empresarial", LocalDateTime.now());
                break;
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCaja;
    private javax.swing.JButton jButtonPreferencial;
    private javax.swing.JButton jButtonServCliente;
    // End of variables declaration//GEN-END:variables
}
